### ISSUE TITLE
"command not found: cargo"?

### ISSUE THREAD

**Issue by Dpmccallum** [sonodima/hitman3_gptk_patcher#1]
I am unsure how to run "cargo build --release"
Could you explain how?

**Comment by sonodima** [comment]
Cargo is automatically installed with Rust using the command:
`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

After executing this command, in the installation dialog select:
1) Proceed with installation (default)

You also need to execute `source "$HOME/.cargo/env"` after it has been installed, or you can just close and reopen the terminal.
